version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      target: development
      args:
        NODE_VERSION: 20
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: development
      args:
        NODE_VERSION: 20
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=personal_assistant
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
      - JWT_SECRET=${JWT_SECRET:-change-me}
      - JWT_EXPIRE=${JWT_EXPIRE:-7d}
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=personal_assistant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  frontend-node-modules:
  backend-node-modules:
  postgres-data:
